# Generated by Django 6.0.4 on 2026-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project Aim / Description', null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/images/')),
                ('project_link', models.URLField(blank=True, help_text='Enter GitHub or Live Project URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technologies', models.ManyToManyField(help_text='Select technologies used in this project', limit_choices_to={'skill_type': 'technical'}, to='skills.skill')),
            ],
        ),
    ]
