# Generated by Django 6.0.4 on 2026-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('10th', 'Secondary Education (10th)'), ('12th', 'Intermediate (12th)'), ('degree', 'Bachelor Degree')], max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('board_or_university', models.CharField(max_length=200)),
                ('year_of_passing', models.CharField(max_length=10)),
                ('percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('marksheet', models.FileField(help_text='Upload PDF or image of marksheet', upload_to='education/marksheets/')),
                ('institution_image', models.ImageField(upload_to='education/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Details',
                'ordering': ['-year_of_passing'],
            },
        ),
    ]
