# Generated by Django 6.0.4 on 2026-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('language', 'Language')], max_length=20)),
                ('skill_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(help_text='Enter rating from 1 to 5')),
                ('description', models.TextField(blank=True, null=True)),
                ('certification', models.FileField(blank=True, help_text='Upload certificate PDF or image', null=True, upload_to='skills/certifications/')),
                ('skill_image', models.ImageField(blank=True, null=True, upload_to='skills/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
